//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CardStatusCodeEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="CardStatusCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Application"/>
 *     &lt;enumeration value="Approved"/>
 *     &lt;enumeration value="Personalised"/>
 *     &lt;enumeration value="Dispatched"/>
 *     &lt;enumeration value="HandedOver"/>
 *     &lt;enumeration value="Confiscated"/>
 *     &lt;enumeration value="Suspended"/>
 *     &lt;enumeration value="Withdrawn"/>
 *     &lt;enumeration value="Surrendered"/>
 *     &lt;enumeration value="Lost"/>
 *     &lt;enumeration value="Stolen"/>
 *     &lt;enumeration value="Malfunctioning"/>
 *     &lt;enumeration value="Expired"/>
 *     &lt;enumeration value="Replaced"/>
 *     &lt;enumeration value="Renewed"/>
 *     &lt;enumeration value="InExchange"/>
 *     &lt;enumeration value="Exchanged"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardStatusCodeEnumType")
@XmlEnum
public enum CardStatusCodeEnumType {

    @XmlEnumValue("Application")
    APPLICATION("Application"), @XmlEnumValue("Approved")
    APPROVED("Approved"), @XmlEnumValue("Personalised")
    PERSONALISED("Personalised"), @XmlEnumValue("Dispatched")
    DISPATCHED("Dispatched"), @XmlEnumValue("HandedOver")
    HANDED_OVER("HandedOver"), @XmlEnumValue("Confiscated")
    CONFISCATED("Confiscated"), @XmlEnumValue("Suspended")
    SUSPENDED("Suspended"), @XmlEnumValue("Withdrawn")
    WITHDRAWN("Withdrawn"), @XmlEnumValue("Surrendered")
    SURRENDERED("Surrendered"), @XmlEnumValue("Lost")
    LOST("Lost"), @XmlEnumValue("Stolen")
    STOLEN("Stolen"), @XmlEnumValue("Malfunctioning")
    MALFUNCTIONING("Malfunctioning"), @XmlEnumValue("Expired")
    EXPIRED("Expired"), @XmlEnumValue("Replaced")
    REPLACED("Replaced"), @XmlEnumValue("Renewed")
    RENEWED("Renewed"), @XmlEnumValue("InExchange")
    IN_EXCHANGE("InExchange"), @XmlEnumValue("Exchanged")
    EXCHANGED("Exchanged");
    private final String value;

    CardStatusCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardStatusCodeEnumType fromValue(String v) {
        for (CardStatusCodeEnumType c : CardStatusCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
