//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for CardDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CardDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="AdditionalCardStatus" type="{urn:eu.cec.tren.tcn}CardStatusCodeEnumType" />
 *       &lt;attribute name="CIA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StatusModifiedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="AdditionalStatusModifiedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardDetailsType")
@XmlSeeAlso( { CardDetailsCCSType.class, CardDetailsCICType.class })
public abstract class CardDetailsType {

    @XmlAttribute(name = "AdditionalCardStatus")
    protected CardStatusCodeEnumType additionalCardStatus;
    @XmlAttribute(name = "CIA", required = true)
    protected String cia;
    @XmlAttribute(name = "StatusModifiedAt", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusModifiedAt;
    @XmlAttribute(name = "AdditionalStatusModifiedAt")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar additionalStatusModifiedAt;

    /**
     * Gets the value of the additionalCardStatus property.
     * 
     * @return possible object is {@link CardStatusCodeEnumType }
     * 
     */
    public CardStatusCodeEnumType getAdditionalCardStatus() {
        return additionalCardStatus;
    }

    /**
     * Sets the value of the additionalCardStatus property.
     * 
     * @param value
     *            allowed object is {@link CardStatusCodeEnumType }
     * 
     */
    public void setAdditionalCardStatus(CardStatusCodeEnumType value) {
        this.additionalCardStatus = value;
    }

    /**
     * Gets the value of the cia property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCIA() {
        return cia;
    }

    /**
     * Sets the value of the cia property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCIA(String value) {
        this.cia = value;
    }

    /**
     * Gets the value of the statusModifiedAt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getStatusModifiedAt() {
        return statusModifiedAt;
    }

    /**
     * Sets the value of the statusModifiedAt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setStatusModifiedAt(XMLGregorianCalendar value) {
        this.statusModifiedAt = value;
    }

    /**
     * Gets the value of the additionalStatusModifiedAt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getAdditionalStatusModifiedAt() {
        return additionalStatusModifiedAt;
    }

    /**
     * Sets the value of the additionalStatusModifiedAt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setAdditionalStatusModifiedAt(XMLGregorianCalendar value) {
        this.additionalStatusModifiedAt = value;
    }

}
