//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CIC_TCN2MS_SearchStatusCodeEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="CIC_TCN2MS_SearchStatusCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Found"/>
 *     &lt;enumeration value="NotFound"/>
 *     &lt;enumeration value="Timeout"/>
 *     &lt;enumeration value="ServerError"/>
 *     &lt;enumeration value="NotAvailable"/>
 *     &lt;enumeration value="NotYetConnected"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CIC_TCN2MS_SearchStatusCodeEnumType")
@XmlEnum
public enum CICTCN2MSSearchStatusCodeEnumType {

    @XmlEnumValue("Found")
    FOUND("Found"), @XmlEnumValue("NotFound")
    NOT_FOUND("NotFound"), @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"), @XmlEnumValue("ServerError")
    SERVER_ERROR("ServerError"), @XmlEnumValue("NotAvailable")
    NOT_AVAILABLE("NotAvailable"), @XmlEnumValue("NotYetConnected")
    NOT_YET_CONNECTED("NotYetConnected");
    private final String value;

    CICTCN2MSSearchStatusCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CICTCN2MSSearchStatusCodeEnumType fromValue(String v) {
        for (CICTCN2MSSearchStatusCodeEnumType c : CICTCN2MSSearchStatusCodeEnumType
                .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
