//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for DrivingLicenseDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DrivingLicenseDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="DLNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DLIssuingNation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DLStatus" type="{urn:eu.cec.tren.tcn}DLStatusCodeEnumType" />
 *       &lt;attribute name="DLIssueDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrivingLicenseDetailsType")
public class DrivingLicenseDetailsType {

    @XmlAttribute(name = "DLNumber", required = true)
    protected String dlNumber;
    @XmlAttribute(name = "DLIssuingNation", required = true)
    protected String dlIssuingNation;
    @XmlAttribute(name = "DLStatus")
    protected DLStatusCodeEnumType dlStatus;
    @XmlAttribute(name = "DLIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dlIssueDate;

    /**
     * Gets the value of the dlNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDLNumber() {
        return dlNumber;
    }

    /**
     * Sets the value of the dlNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDLNumber(String value) {
        this.dlNumber = value;
    }

    /**
     * Gets the value of the dlIssuingNation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDLIssuingNation() {
        return dlIssuingNation;
    }

    /**
     * Sets the value of the dlIssuingNation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDLIssuingNation(String value) {
        this.dlIssuingNation = value;
    }

    /**
     * Gets the value of the dlStatus property.
     * 
     * @return possible object is {@link DLStatusCodeEnumType }
     * 
     */
    public DLStatusCodeEnumType getDLStatus() {
        return dlStatus;
    }

    /**
     * Sets the value of the dlStatus property.
     * 
     * @param value
     *            allowed object is {@link DLStatusCodeEnumType }
     * 
     */
    public void setDLStatus(DLStatusCodeEnumType value) {
        this.dlStatus = value;
    }

    /**
     * Gets the value of the dlIssueDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDLIssueDate() {
        return dlIssueDate;
    }

    /**
     * Sets the value of the dlIssueDate property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDLIssueDate(XMLGregorianCalendar value) {
        this.dlIssueDate = value;
    }

}
