//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DriverDetailsCCSType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DriverDetailsCCSType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}DriverDetailsType">
 *       &lt;sequence>
 *         &lt;element name="DrivingLicenseDetails" type="{urn:eu.cec.tren.tcn}DrivingLicenseDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DriverDetailsCCSType", propOrder = { "drivingLicenseDetails" })
public class DriverDetailsCCSType extends DriverDetailsType {

    @XmlElement(name = "DrivingLicenseDetails", required = true)
    protected DrivingLicenseDetailsType drivingLicenseDetails;

    /**
     * Gets the value of the drivingLicenseDetails property.
     * 
     * @return possible object is {@link DrivingLicenseDetailsType }
     * 
     */
    public DrivingLicenseDetailsType getDrivingLicenseDetails() {
        return drivingLicenseDetails;
    }

    /**
     * Sets the value of the drivingLicenseDetails property.
     * 
     * @param value
     *            allowed object is {@link DrivingLicenseDetailsType }
     * 
     */
    public void setDrivingLicenseDetails(DrivingLicenseDetailsType value) {
        this.drivingLicenseDetails = value;
    }

}
