//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Header_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Header_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}HeaderType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="MSRefId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TCNRefId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StatusCode" use="required" type="{urn:eu.cec.tren.tcn}StatusCodeEnumType" />
 *       &lt;attribute name="StatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header_ResType")
public class HeaderResType extends HeaderType {

    @XmlAttribute(name = "MSRefId", required = true)
    protected String msRefId;
    @XmlAttribute(name = "TCNRefId", required = true)
    protected String tcnRefId;
    @XmlAttribute(name = "StatusCode", required = true)
    protected StatusCodeEnumType statusCode;
    @XmlAttribute(name = "StatusMessage")
    protected String statusMessage;

    /**
     * Gets the value of the msRefId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMSRefId() {
        return msRefId;
    }

    /**
     * Sets the value of the msRefId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMSRefId(String value) {
        this.msRefId = value;
    }

    /**
     * Gets the value of the tcnRefId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTCNRefId() {
        return tcnRefId;
    }

    /**
     * Sets the value of the tcnRefId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTCNRefId(String value) {
        this.tcnRefId = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return possible object is {@link StatusCodeEnumType }
     * 
     */
    public StatusCodeEnumType getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *            allowed object is {@link StatusCodeEnumType }
     * 
     */
    public void setStatusCode(StatusCodeEnumType value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

}
