//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for HeaderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.4" />
 *       &lt;attribute name="TestId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SentAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="From" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="To" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderType")
@XmlSeeAlso( { HeaderMS2TCNReqType.class, HeaderResType.class,
        HeaderTCN2MSReqType.class })
public abstract class HeaderType {

    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "TestId")
    protected String testId;
    @XmlAttribute(name = "SentAt", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentAt;
    @XmlAttribute(name = "From", required = true)
    protected String from;
    @XmlAttribute(name = "To", required = true)
    protected String to;

    /**
     * Gets the value of the version property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersion() {
        if (version == null) {
            return "1.4";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the testId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTestId() {
        return testId;
    }

    /**
     * Sets the value of the testId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTestId(String value) {
        this.testId = value;
    }

    /**
     * Gets the value of the sentAt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getSentAt() {
        return sentAt;
    }

    /**
     * Sets the value of the sentAt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setSentAt(XMLGregorianCalendar value) {
        this.sentAt = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTo(String value) {
        this.to = value;
    }

}
