//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ICDL_TCN2MS_StatusCodeEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ICDL_TCN2MS_StatusCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="DrivingLicenseNumberNotFound"/>
 *     &lt;enumeration value="Timeout"/>
 *     &lt;enumeration value="ServerError"/>
 *     &lt;enumeration value="NotProcessed"/>
 *     &lt;enumeration value="NotAvailable"/>
 *     &lt;enumeration value="NotYetConnected"/>
 *     &lt;enumeration value="DrivingLicenseNumberInvalid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ICDL_TCN2MS_StatusCodeEnumType")
@XmlEnum
public enum ICDLTCN2MSStatusCodeEnumType {

    OK("OK"), @XmlEnumValue("DrivingLicenseNumberNotFound")
    DRIVING_LICENSE_NUMBER_NOT_FOUND("DrivingLicenseNumberNotFound"), @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"), @XmlEnumValue("ServerError")
    SERVER_ERROR("ServerError"), @XmlEnumValue("NotProcessed")
    NOT_PROCESSED("NotProcessed"), @XmlEnumValue("NotAvailable")
    NOT_AVAILABLE("NotAvailable"), @XmlEnumValue("NotYetConnected")
    NOT_YET_CONNECTED("NotYetConnected"), @XmlEnumValue("DrivingLicenseNumberInvalid")
    DRIVING_LICENSE_NUMBER_INVALID("DrivingLicenseNumberInvalid");
    private final String value;

    ICDLTCN2MSStatusCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ICDLTCN2MSStatusCodeEnumType fromValue(String v) {
        for (ICDLTCN2MSStatusCodeEnumType c : ICDLTCN2MSStatusCodeEnumType
                .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
