//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IssuedCard_MS2TCN_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="IssuedCard_MS2TCN_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}IssuedCardType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="IssuedCardDLStatusCode" use="required" type="{urn:eu.cec.tren.tcn}ICDL_MS2TCN_StatusCodeEnumType" />
 *       &lt;attribute name="IssuedCardDLStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssuedCard_MS2TCN_ResType")
public class IssuedCardMS2TCNResType extends IssuedCardType {

    @XmlAttribute(name = "IssuedCardDLStatusCode", required = true)
    protected ICDLMS2TCNStatusCodeEnumType issuedCardDLStatusCode;
    @XmlAttribute(name = "IssuedCardDLStatusMessage")
    protected String issuedCardDLStatusMessage;

    /**
     * Gets the value of the issuedCardDLStatusCode property.
     * 
     * @return possible object is {@link ICDLMS2TCNStatusCodeEnumType }
     * 
     */
    public ICDLMS2TCNStatusCodeEnumType getIssuedCardDLStatusCode() {
        return issuedCardDLStatusCode;
    }

    /**
     * Sets the value of the issuedCardDLStatusCode property.
     * 
     * @param value
     *            allowed object is {@link ICDLMS2TCNStatusCodeEnumType }
     * 
     */
    public void setIssuedCardDLStatusCode(ICDLMS2TCNStatusCodeEnumType value) {
        this.issuedCardDLStatusCode = value;
    }

    /**
     * Gets the value of the issuedCardDLStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuedCardDLStatusMessage() {
        return issuedCardDLStatusMessage;
    }

    /**
     * Sets the value of the issuedCardDLStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuedCardDLStatusMessage(String value) {
        this.issuedCardDLStatusMessage = value;
    }

}
