//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IssuedCardType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="IssuedCardType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="IssuedCardNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssuingMemberStateCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DrivingLicenseNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssuedCardType")
@XmlSeeAlso( { IssuedCardMS2TCNResType.class, IssuedCardMS2TCNReqType.class })
public class IssuedCardType {

    @XmlAttribute(name = "IssuedCardNumber", required = true)
    protected String issuedCardNumber;
    @XmlAttribute(name = "IssuingMemberStateCode", required = true)
    protected String issuingMemberStateCode;
    @XmlAttribute(name = "DrivingLicenseNumber", required = true)
    protected String drivingLicenseNumber;

    /**
     * Gets the value of the issuedCardNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuedCardNumber() {
        return issuedCardNumber;
    }

    /**
     * Sets the value of the issuedCardNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuedCardNumber(String value) {
        this.issuedCardNumber = value;
    }

    /**
     * Gets the value of the issuingMemberStateCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuingMemberStateCode() {
        return issuingMemberStateCode;
    }

    /**
     * Sets the value of the issuingMemberStateCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuingMemberStateCode(String value) {
        this.issuingMemberStateCode = value;
    }

    /**
     * Gets the value of the drivingLicenseNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDrivingLicenseNumber() {
        return drivingLicenseNumber;
    }

    /**
     * Sets the value of the drivingLicenseNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDrivingLicenseNumber(String value) {
        this.drivingLicenseNumber = value;
    }

}
