//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MCS_TCN2MS_StatusCodeEnumType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="MCS_TCN2MS_StatusCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="CardNumberNotFound"/>
 *     &lt;enumeration value="CardStatusInvalid"/>
 *     &lt;enumeration value="Timeout"/>
 *     &lt;enumeration value="ServerError"/>
 *     &lt;enumeration value="NotAvailable"/>
 *     &lt;enumeration value="NotYetConnected"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MCS_TCN2MS_StatusCodeEnumType")
@XmlEnum
public enum MCSTCN2MSStatusCodeEnumType {

    OK("OK"), @XmlEnumValue("CardNumberNotFound")
    CARD_NUMBER_NOT_FOUND("CardNumberNotFound"), @XmlEnumValue("CardStatusInvalid")
    CARD_STATUS_INVALID("CardStatusInvalid"), @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"), @XmlEnumValue("ServerError")
    SERVER_ERROR("ServerError"), @XmlEnumValue("NotAvailable")
    NOT_AVAILABLE("NotAvailable"), @XmlEnumValue("NotYetConnected")
    NOT_YET_CONNECTED("NotYetConnected");
    private final String value;

    MCSTCN2MSStatusCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MCSTCN2MSStatusCodeEnumType fromValue(String v) {
        for (MCSTCN2MSStatusCodeEnumType c : MCSTCN2MSStatusCodeEnumType
                .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
