//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModCardDetails_MS2TCN_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModCardDetails_MS2TCN_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}ModCardDetails_TCN2MS_ReqType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="ModStatusCode" use="required" type="{urn:eu.cec.tren.tcn}MCS_MS2TCN_StatusCodeEnumType" />
 *       &lt;attribute name="ModStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModCardDetails_MS2TCN_ResType")
public class ModCardDetailsMS2TCNResType extends ModCardDetailsTCN2MSReqType {

    @XmlAttribute(name = "ModStatusCode", required = true)
    protected MCSMS2TCNStatusCodeEnumType modStatusCode;
    @XmlAttribute(name = "ModStatusMessage")
    protected String modStatusMessage;

    /**
     * Gets the value of the modStatusCode property.
     * 
     * @return possible object is {@link MCSMS2TCNStatusCodeEnumType }
     * 
     */
    public MCSMS2TCNStatusCodeEnumType getModStatusCode() {
        return modStatusCode;
    }

    /**
     * Sets the value of the modStatusCode property.
     * 
     * @param value
     *            allowed object is {@link MCSMS2TCNStatusCodeEnumType }
     * 
     */
    public void setModStatusCode(MCSMS2TCNStatusCodeEnumType value) {
        this.modStatusCode = value;
    }

    /**
     * Gets the value of the modStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModStatusMessage() {
        return modStatusMessage;
    }

    /**
     * Sets the value of the modStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModStatusMessage(String value) {
        this.modStatusMessage = value;
    }

}
