//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModCardDetails_TCN2MS_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModCardDetails_TCN2MS_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}ModCardDetails_MS2TCN_ReqType">
 *       &lt;sequence>
 *         &lt;element name="MSContactInfo" type="{urn:eu.cec.tren.tcn}MSContactInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ModStatusCode" use="required" type="{urn:eu.cec.tren.tcn}MCS_TCN2MS_StatusCodeEnumType" />
 *       &lt;attribute name="ModStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModCardDetails_TCN2MS_ResType", propOrder = { "msContactInfo" })
public class ModCardDetailsTCN2MSResType extends ModCardDetailsMS2TCNReqType {

    @XmlElement(name = "MSContactInfo")
    protected MSContactInfoType msContactInfo;
    @XmlAttribute(name = "ModStatusCode", required = true)
    protected MCSTCN2MSStatusCodeEnumType modStatusCode;
    @XmlAttribute(name = "ModStatusMessage")
    protected String modStatusMessage;

    /**
     * Gets the value of the msContactInfo property.
     * 
     * @return possible object is {@link MSContactInfoType }
     * 
     */
    public MSContactInfoType getMSContactInfo() {
        return msContactInfo;
    }

    /**
     * Sets the value of the msContactInfo property.
     * 
     * @param value
     *            allowed object is {@link MSContactInfoType }
     * 
     */
    public void setMSContactInfo(MSContactInfoType value) {
        this.msContactInfo = value;
    }

    /**
     * Gets the value of the modStatusCode property.
     * 
     * @return possible object is {@link MCSTCN2MSStatusCodeEnumType }
     * 
     */
    public MCSTCN2MSStatusCodeEnumType getModStatusCode() {
        return modStatusCode;
    }

    /**
     * Sets the value of the modStatusCode property.
     * 
     * @param value
     *            allowed object is {@link MCSTCN2MSStatusCodeEnumType }
     * 
     */
    public void setModStatusCode(MCSTCN2MSStatusCodeEnumType value) {
        this.modStatusCode = value;
    }

    /**
     * Gets the value of the modStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getModStatusMessage() {
        return modStatusMessage;
    }

    /**
     * Sets the value of the modStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setModStatusMessage(String value) {
        this.modStatusMessage = value;
    }

}
