//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ModCardDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModCardDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="CardNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NewCardStatus" use="required" type="{urn:eu.cec.tren.tcn}NewCardStatusCodeEnumType" />
 *       &lt;attribute name="Reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StatusModifiedAt" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ReasonCode" type="{urn:eu.cec.tren.tcn}MCS_ReasonCodeEnumType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModCardDetailsType")
@XmlSeeAlso( { ModCardDetailsTCN2MSReqType.class,
        ModCardDetailsMS2TCNReqType.class })
public class ModCardDetailsType {

    @XmlAttribute(name = "CardNumber", required = true)
    protected String cardNumber;
    @XmlAttribute(name = "NewCardStatus", required = true)
    protected NewCardStatusCodeEnumType newCardStatus;
    @XmlAttribute(name = "Reason")
    protected String reason;
    @XmlAttribute(name = "StatusModifiedAt", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusModifiedAt;
    @XmlAttribute(name = "ReasonCode")
    protected MCSReasonCodeEnumType reasonCode;

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the newCardStatus property.
     * 
     * @return possible object is {@link NewCardStatusCodeEnumType }
     * 
     */
    public NewCardStatusCodeEnumType getNewCardStatus() {
        return newCardStatus;
    }

    /**
     * Sets the value of the newCardStatus property.
     * 
     * @param value
     *            allowed object is {@link NewCardStatusCodeEnumType }
     * 
     */
    public void setNewCardStatus(NewCardStatusCodeEnumType value) {
        this.newCardStatus = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the statusModifiedAt property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getStatusModifiedAt() {
        return statusModifiedAt;
    }

    /**
     * Sets the value of the statusModifiedAt property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setStatusModifiedAt(XMLGregorianCalendar value) {
        this.statusModifiedAt = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return possible object is {@link MCSReasonCodeEnumType }
     * 
     */
    public MCSReasonCodeEnumType getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *            allowed object is {@link MCSReasonCodeEnumType }
     * 
     */
    public void setReasonCode(MCSReasonCodeEnumType value) {
        this.reasonCode = value;
    }

}
