//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.iba.tachonet.OutgoingMessage;

/**
 * <p>
 * Java class for MS2TCN_CheckCardStatus_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MS2TCN_CheckCardStatus_ResType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{urn:eu.cec.tren.tcn}Header_ResType"/>
 *         &lt;element name="Body" type="{urn:eu.cec.tren.tcn}MS2TCN_CheckCardStatus_ResBodyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MS2TCN_CheckCardStatus_ResType", propOrder = { "header",
        "body" })
public class MS2TCNCheckCardStatusResType implements OutgoingMessage {

    @XmlElement(name = "Header", required = true)
    protected HeaderResType header;
    @XmlElement(name = "Body")
    protected MS2TCNCheckCardStatusResBodyType body;

    /**
     * Gets the value of the header property.
     * 
     * @return possible object is {@link HeaderResType }
     * 
     */
    public HeaderResType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *            allowed object is {@link HeaderResType }
     * 
     */
    public void setHeader(HeaderResType value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return possible object is {@link MS2TCNCheckCardStatusResBodyType }
     * 
     */
    public MS2TCNCheckCardStatusResBodyType getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *            allowed object is {@link MS2TCNCheckCardStatusResBodyType }
     * 
     */
    public void setBody(MS2TCNCheckCardStatusResBodyType value) {
        this.body = value;
    }

}
