//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.iba.tachonet.bean package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MS2TCNModCardStatusRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_ModCardStatus_Res");
    private final static QName _MS2TCNModCardStatusReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_ModCardStatus_Req");
    private final static QName _MS2TCNIssuedCardDLReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_IssuedCardDL_Req");
    private final static QName _TCN2MSModCardStatusReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_ModCardStatus_Req");
    private final static QName _TCN2MSModCardStatusRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_ModCardStatus_Res");
    private final static QName _MS2TCNCheckCardStatusReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_CheckCardStatus_Req");
    private final static QName _TCN2MSCheckCardStatusReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_CheckCardStatus_Req");
    private final static QName _MS2TCNCheckCardStatusRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_CheckCardStatus_Res");
    private final static QName _TCN2MSCheckIssuedCardsRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_CheckIssuedCards_Res");
    private final static QName _TCN2MSCheckCardStatusRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_CheckCardStatus_Res");
    private final static QName _MS2TCNIssuedCardDLRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_IssuedCardDL_Res");
    private final static QName _TCN2MSCheckIssuedCardsReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_CheckIssuedCards_Req");
    private final static QName _TCN2MSIssuedCardDLRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_IssuedCardDL_Res");
    private final static QName _MS2TCNCheckIssuedCardsReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_CheckIssuedCards_Req");
    private final static QName _TCN2MSIssuedCardDLReq_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN2MS_IssuedCardDL_Req");
    private final static QName _TCNReceipt_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "TCN_Receipt");
    private final static QName _MS2TCNCheckIssuedCardsRes_QNAME = new QName(
            "urn:eu.cec.tren.tcn", "MS2TCN_CheckIssuedCards_Res");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.iba.tachonet.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MS2TCNCheckIssuedCardsResBodyType }
     * 
     */
    public MS2TCNCheckIssuedCardsResBodyType createMS2TCNCheckIssuedCardsResBodyType() {
        return new MS2TCNCheckIssuedCardsResBodyType();
    }

    /**
     * Create an instance of {@link DeclaredByMSType }
     * 
     */
    public DeclaredByMSType createDeclaredByMSType() {
        return new DeclaredByMSType();
    }

    /**
     * Create an instance of {@link SearchCriteriaMS2TCNResType }
     * 
     */
    public SearchCriteriaMS2TCNResType createSearchCriteriaMS2TCNResType() {
        return new SearchCriteriaMS2TCNResType();
    }

    /**
     * Create an instance of {@link MSContactInfoType }
     * 
     */
    public MSContactInfoType createMSContactInfoType() {
        return new MSContactInfoType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckCardStatusResBodyType }
     * 
     */
    public MS2TCNCheckCardStatusResBodyType createMS2TCNCheckCardStatusResBodyType() {
        return new MS2TCNCheckCardStatusResBodyType();
    }

    /**
     * Create an instance of {@link WorkshopDetailsType }
     * 
     */
    public WorkshopDetailsType createWorkshopDetailsType() {
        return new WorkshopDetailsType();
    }

    /**
     * Create an instance of {@link MS2TCNIssuedCardDLReqType }
     * 
     */
    public MS2TCNIssuedCardDLReqType createMS2TCNIssuedCardDLReqType() {
        return new MS2TCNIssuedCardDLReqType();
    }

    /**
     * Create an instance of {@link IssuedCardMS2TCNReqType }
     * 
     */
    public IssuedCardMS2TCNReqType createIssuedCardMS2TCNReqType() {
        return new IssuedCardMS2TCNReqType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckIssuedCardsReqType }
     * 
     */
    public TCN2MSCheckIssuedCardsReqType createTCN2MSCheckIssuedCardsReqType() {
        return new TCN2MSCheckIssuedCardsReqType();
    }

    /**
     * Create an instance of {@link MS2TCNModCardStatusReqBodyType }
     * 
     */
    public MS2TCNModCardStatusReqBodyType createMS2TCNModCardStatusReqBodyType() {
        return new MS2TCNModCardStatusReqBodyType();
    }

    /**
     * Create an instance of {@link CardDetailsCCSType }
     * 
     */
    public CardDetailsCCSType createCardDetailsCCSType() {
        return new CardDetailsCCSType();
    }

    /**
     * Create an instance of {@link SearchedDriverTCN2MSReqType }
     * 
     */
    public SearchedDriverTCN2MSReqType createSearchedDriverTCN2MSReqType() {
        return new SearchedDriverTCN2MSReqType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckIssuedCardsResBodyType }
     * 
     */
    public TCN2MSCheckIssuedCardsResBodyType createTCN2MSCheckIssuedCardsResBodyType() {
        return new TCN2MSCheckIssuedCardsResBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNIssuedCardDLReqBodyType }
     * 
     */
    public MS2TCNIssuedCardDLReqBodyType createMS2TCNIssuedCardDLReqBodyType() {
        return new MS2TCNIssuedCardDLReqBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckIssuedCardsReqBodyType }
     * 
     */
    public MS2TCNCheckIssuedCardsReqBodyType createMS2TCNCheckIssuedCardsReqBodyType() {
        return new MS2TCNCheckIssuedCardsReqBodyType();
    }

    /**
     * Create an instance of {@link ModCardDetailsTCN2MSResType }
     * 
     */
    public ModCardDetailsTCN2MSResType createModCardDetailsTCN2MSResType() {
        return new ModCardDetailsTCN2MSResType();
    }

    /**
     * Create an instance of {@link DriverDetailsCCSType }
     * 
     */
    public DriverDetailsCCSType createDriverDetailsCCSType() {
        return new DriverDetailsCCSType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckIssuedCardsResType }
     * 
     */
    public TCN2MSCheckIssuedCardsResType createTCN2MSCheckIssuedCardsResType() {
        return new TCN2MSCheckIssuedCardsResType();
    }

    /**
     * Create an instance of {@link TCN2MSIssuedCardDLResBodyType }
     * 
     */
    public TCN2MSIssuedCardDLResBodyType createTCN2MSIssuedCardDLResBodyType() {
        return new TCN2MSIssuedCardDLResBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNIssuedCardDLResType }
     * 
     */
    public MS2TCNIssuedCardDLResType createMS2TCNIssuedCardDLResType() {
        return new MS2TCNIssuedCardDLResType();
    }

    /**
     * Create an instance of {@link SearchCriteriaType }
     * 
     */
    public SearchCriteriaType createSearchCriteriaType() {
        return new SearchCriteriaType();
    }

    /**
     * Create an instance of {@link TCN2MSIssuedCardDLReqType }
     * 
     */
    public TCN2MSIssuedCardDLReqType createTCN2MSIssuedCardDLReqType() {
        return new TCN2MSIssuedCardDLReqType();
    }

    /**
     * Create an instance of {@link ModCardDetailsMS2TCNReqType }
     * 
     */
    public ModCardDetailsMS2TCNReqType createModCardDetailsMS2TCNReqType() {
        return new ModCardDetailsMS2TCNReqType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckIssuedCardsReqBodyType }
     * 
     */
    public TCN2MSCheckIssuedCardsReqBodyType createTCN2MSCheckIssuedCardsReqBodyType() {
        return new TCN2MSCheckIssuedCardsReqBodyType();
    }

    /**
     * Create an instance of {@link TCNReceiptType }
     * 
     */
    public TCNReceiptType createTCNReceiptType() {
        return new TCNReceiptType();
    }

    /**
     * Create an instance of {@link HeaderTCN2MSReqType }
     * 
     */
    public HeaderTCN2MSReqType createHeaderTCN2MSReqType() {
        return new HeaderTCN2MSReqType();
    }

    /**
     * Create an instance of {@link IssuedCardTCN2MSResType }
     * 
     */
    public IssuedCardTCN2MSResType createIssuedCardTCN2MSResType() {
        return new IssuedCardTCN2MSResType();
    }

    /**
     * Create an instance of {@link DrivingLicenseDetailsType }
     * 
     */
    public DrivingLicenseDetailsType createDrivingLicenseDetailsType() {
        return new DrivingLicenseDetailsType();
    }

    /**
     * Create an instance of {@link MemberStateType }
     * 
     */
    public MemberStateType createMemberStateType() {
        return new MemberStateType();
    }

    /**
     * Create an instance of {@link SearchedDriverTCN2MSResType }
     * 
     */
    public SearchedDriverTCN2MSResType createSearchedDriverTCN2MSResType() {
        return new SearchedDriverTCN2MSResType();
    }

    /**
     * Create an instance of {@link TCN2MSIssuedCardDLReqBodyType }
     * 
     */
    public TCN2MSIssuedCardDLReqBodyType createTCN2MSIssuedCardDLReqBodyType() {
        return new TCN2MSIssuedCardDLReqBodyType();
    }

    /**
     * Create an instance of {@link TCN2MSIssuedCardDLResType }
     * 
     */
    public TCN2MSIssuedCardDLResType createTCN2MSIssuedCardDLResType() {
        return new TCN2MSIssuedCardDLResType();
    }

    /**
     * Create an instance of {@link SearchedDriverMS2TCNResType }
     * 
     */
    public SearchedDriverMS2TCNResType createSearchedDriverMS2TCNResType() {
        return new SearchedDriverMS2TCNResType();
    }

    /**
     * Create an instance of {@link SearchedDriverMS2TCNReqType }
     * 
     */
    public SearchedDriverMS2TCNReqType createSearchedDriverMS2TCNReqType() {
        return new SearchedDriverMS2TCNReqType();
    }

    /**
     * Create an instance of {@link ModCardDetailsTCN2MSReqType }
     * 
     */
    public ModCardDetailsTCN2MSReqType createModCardDetailsTCN2MSReqType() {
        return new ModCardDetailsTCN2MSReqType();
    }

    /**
     * Create an instance of {@link HeaderMS2TCNReqType }
     * 
     */
    public HeaderMS2TCNReqType createHeaderMS2TCNReqType() {
        return new HeaderMS2TCNReqType();
    }

    /**
     * Create an instance of {@link SearchCriteriaMS2TCNReqType }
     * 
     */
    public SearchCriteriaMS2TCNReqType createSearchCriteriaMS2TCNReqType() {
        return new SearchCriteriaMS2TCNReqType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckCardStatusReqBodyType }
     * 
     */
    public TCN2MSCheckCardStatusReqBodyType createTCN2MSCheckCardStatusReqBodyType() {
        return new TCN2MSCheckCardStatusReqBodyType();
    }

    /**
     * Create an instance of {@link TCN2MSModCardStatusResBodyType }
     * 
     */
    public TCN2MSModCardStatusResBodyType createTCN2MSModCardStatusResBodyType() {
        return new TCN2MSModCardStatusResBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckIssuedCardsReqType }
     * 
     */
    public MS2TCNCheckIssuedCardsReqType createMS2TCNCheckIssuedCardsReqType() {
        return new MS2TCNCheckIssuedCardsReqType();
    }

    /**
     * Create an instance of {@link DeclaredByType }
     * 
     */
    public DeclaredByType createDeclaredByType() {
        return new DeclaredByType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckCardStatusReqType }
     * 
     */
    public TCN2MSCheckCardStatusReqType createTCN2MSCheckCardStatusReqType() {
        return new TCN2MSCheckCardStatusReqType();
    }

    /**
     * Create an instance of {@link IssuedCardMS2TCNResType }
     * 
     */
    public IssuedCardMS2TCNResType createIssuedCardMS2TCNResType() {
        return new IssuedCardMS2TCNResType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckCardStatusReqType }
     * 
     */
    public MS2TCNCheckCardStatusReqType createMS2TCNCheckCardStatusReqType() {
        return new MS2TCNCheckCardStatusReqType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckIssuedCardsResType }
     * 
     */
    public MS2TCNCheckIssuedCardsResType createMS2TCNCheckIssuedCardsResType() {
        return new MS2TCNCheckIssuedCardsResType();
    }

    /**
     * Create an instance of {@link HeaderResType }
     * 
     */
    public HeaderResType createHeaderResType() {
        return new HeaderResType();
    }

    /**
     * Create an instance of {@link TCN2MSModCardStatusReqBodyType }
     * 
     */
    public TCN2MSModCardStatusReqBodyType createTCN2MSModCardStatusReqBodyType() {
        return new TCN2MSModCardStatusReqBodyType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckCardStatusResBodyType }
     * 
     */
    public TCN2MSCheckCardStatusResBodyType createTCN2MSCheckCardStatusResBodyType() {
        return new TCN2MSCheckCardStatusResBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNModCardStatusResBodyType }
     * 
     */
    public MS2TCNModCardStatusResBodyType createMS2TCNModCardStatusResBodyType() {
        return new MS2TCNModCardStatusResBodyType();
    }

    /**
     * Create an instance of {@link TCN2MSModCardStatusResType }
     * 
     */
    public TCN2MSModCardStatusResType createTCN2MSModCardStatusResType() {
        return new TCN2MSModCardStatusResType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckCardStatusResType }
     * 
     */
    public MS2TCNCheckCardStatusResType createMS2TCNCheckCardStatusResType() {
        return new MS2TCNCheckCardStatusResType();
    }

    /**
     * Create an instance of {@link ModCardDetailsMS2TCNResType }
     * 
     */
    public ModCardDetailsMS2TCNResType createModCardDetailsMS2TCNResType() {
        return new ModCardDetailsMS2TCNResType();
    }

    /**
     * Create an instance of {@link IssuedCardType }
     * 
     */
    public IssuedCardType createIssuedCardType() {
        return new IssuedCardType();
    }

    /**
     * Create an instance of {@link DriverDetailsCICType }
     * 
     */
    public DriverDetailsCICType createDriverDetailsCICType() {
        return new DriverDetailsCICType();
    }

    /**
     * Create an instance of {@link TCN2MSModCardStatusReqType }
     * 
     */
    public TCN2MSModCardStatusReqType createTCN2MSModCardStatusReqType() {
        return new TCN2MSModCardStatusReqType();
    }

    /**
     * Create an instance of {@link TCN2MSCheckCardStatusResType }
     * 
     */
    public TCN2MSCheckCardStatusResType createTCN2MSCheckCardStatusResType() {
        return new TCN2MSCheckCardStatusResType();
    }

    /**
     * Create an instance of {@link MS2TCNIssuedCardDLResBodyType }
     * 
     */
    public MS2TCNIssuedCardDLResBodyType createMS2TCNIssuedCardDLResBodyType() {
        return new MS2TCNIssuedCardDLResBodyType();
    }

    /**
     * Create an instance of {@link MS2TCNModCardStatusResType }
     * 
     */
    public MS2TCNModCardStatusResType createMS2TCNModCardStatusResType() {
        return new MS2TCNModCardStatusResType();
    }

    /**
     * Create an instance of {@link CardDetailsCICType }
     * 
     */
    public CardDetailsCICType createCardDetailsCICType() {
        return new CardDetailsCICType();
    }

    /**
     * Create an instance of {@link ModCardDetailsType }
     * 
     */
    public ModCardDetailsType createModCardDetailsType() {
        return new ModCardDetailsType();
    }

    /**
     * Create an instance of {@link MS2TCNModCardStatusReqType }
     * 
     */
    public MS2TCNModCardStatusReqType createMS2TCNModCardStatusReqType() {
        return new MS2TCNModCardStatusReqType();
    }

    /**
     * Create an instance of {@link MS2TCNCheckCardStatusReqBodyType }
     * 
     */
    public MS2TCNCheckCardStatusReqBodyType createMS2TCNCheckCardStatusReqBodyType() {
        return new MS2TCNCheckCardStatusReqBodyType();
    }

    /**
     * Create an instance of {@link SearchCriteriaTCN2MSResType }
     * 
     */
    public SearchCriteriaTCN2MSResType createSearchCriteriaTCN2MSResType() {
        return new SearchCriteriaTCN2MSResType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNModCardStatusResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_ModCardStatus_Res")
    public JAXBElement<MS2TCNModCardStatusResType> createMS2TCNModCardStatusRes(
            MS2TCNModCardStatusResType value) {
        return new JAXBElement<MS2TCNModCardStatusResType>(
                _MS2TCNModCardStatusRes_QNAME,
                MS2TCNModCardStatusResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNModCardStatusReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_ModCardStatus_Req")
    public JAXBElement<MS2TCNModCardStatusReqType> createMS2TCNModCardStatusReq(
            MS2TCNModCardStatusReqType value) {
        return new JAXBElement<MS2TCNModCardStatusReqType>(
                _MS2TCNModCardStatusReq_QNAME,
                MS2TCNModCardStatusReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNIssuedCardDLReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_IssuedCardDL_Req")
    public JAXBElement<MS2TCNIssuedCardDLReqType> createMS2TCNIssuedCardDLReq(
            MS2TCNIssuedCardDLReqType value) {
        return new JAXBElement<MS2TCNIssuedCardDLReqType>(
                _MS2TCNIssuedCardDLReq_QNAME, MS2TCNIssuedCardDLReqType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSModCardStatusReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_ModCardStatus_Req")
    public JAXBElement<TCN2MSModCardStatusReqType> createTCN2MSModCardStatusReq(
            TCN2MSModCardStatusReqType value) {
        return new JAXBElement<TCN2MSModCardStatusReqType>(
                _TCN2MSModCardStatusReq_QNAME,
                TCN2MSModCardStatusReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSModCardStatusResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_ModCardStatus_Res")
    public JAXBElement<TCN2MSModCardStatusResType> createTCN2MSModCardStatusRes(
            TCN2MSModCardStatusResType value) {
        return new JAXBElement<TCN2MSModCardStatusResType>(
                _TCN2MSModCardStatusRes_QNAME,
                TCN2MSModCardStatusResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNCheckCardStatusReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_CheckCardStatus_Req")
    public JAXBElement<MS2TCNCheckCardStatusReqType> createMS2TCNCheckCardStatusReq(
            MS2TCNCheckCardStatusReqType value) {
        return new JAXBElement<MS2TCNCheckCardStatusReqType>(
                _MS2TCNCheckCardStatusReq_QNAME,
                MS2TCNCheckCardStatusReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSCheckCardStatusReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_CheckCardStatus_Req")
    public JAXBElement<TCN2MSCheckCardStatusReqType> createTCN2MSCheckCardStatusReq(
            TCN2MSCheckCardStatusReqType value) {
        return new JAXBElement<TCN2MSCheckCardStatusReqType>(
                _TCN2MSCheckCardStatusReq_QNAME,
                TCN2MSCheckCardStatusReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNCheckCardStatusResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_CheckCardStatus_Res")
    public JAXBElement<MS2TCNCheckCardStatusResType> createMS2TCNCheckCardStatusRes(
            MS2TCNCheckCardStatusResType value) {
        return new JAXBElement<MS2TCNCheckCardStatusResType>(
                _MS2TCNCheckCardStatusRes_QNAME,
                MS2TCNCheckCardStatusResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSCheckIssuedCardsResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_CheckIssuedCards_Res")
    public JAXBElement<TCN2MSCheckIssuedCardsResType> createTCN2MSCheckIssuedCardsRes(
            TCN2MSCheckIssuedCardsResType value) {
        return new JAXBElement<TCN2MSCheckIssuedCardsResType>(
                _TCN2MSCheckIssuedCardsRes_QNAME,
                TCN2MSCheckIssuedCardsResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSCheckCardStatusResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_CheckCardStatus_Res")
    public JAXBElement<TCN2MSCheckCardStatusResType> createTCN2MSCheckCardStatusRes(
            TCN2MSCheckCardStatusResType value) {
        return new JAXBElement<TCN2MSCheckCardStatusResType>(
                _TCN2MSCheckCardStatusRes_QNAME,
                TCN2MSCheckCardStatusResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNIssuedCardDLResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_IssuedCardDL_Res")
    public JAXBElement<MS2TCNIssuedCardDLResType> createMS2TCNIssuedCardDLRes(
            MS2TCNIssuedCardDLResType value) {
        return new JAXBElement<MS2TCNIssuedCardDLResType>(
                _MS2TCNIssuedCardDLRes_QNAME, MS2TCNIssuedCardDLResType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSCheckIssuedCardsReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_CheckIssuedCards_Req")
    public JAXBElement<TCN2MSCheckIssuedCardsReqType> createTCN2MSCheckIssuedCardsReq(
            TCN2MSCheckIssuedCardsReqType value) {
        return new JAXBElement<TCN2MSCheckIssuedCardsReqType>(
                _TCN2MSCheckIssuedCardsReq_QNAME,
                TCN2MSCheckIssuedCardsReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSIssuedCardDLResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_IssuedCardDL_Res")
    public JAXBElement<TCN2MSIssuedCardDLResType> createTCN2MSIssuedCardDLRes(
            TCN2MSIssuedCardDLResType value) {
        return new JAXBElement<TCN2MSIssuedCardDLResType>(
                _TCN2MSIssuedCardDLRes_QNAME, TCN2MSIssuedCardDLResType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNCheckIssuedCardsReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_CheckIssuedCards_Req")
    public JAXBElement<MS2TCNCheckIssuedCardsReqType> createMS2TCNCheckIssuedCardsReq(
            MS2TCNCheckIssuedCardsReqType value) {
        return new JAXBElement<MS2TCNCheckIssuedCardsReqType>(
                _MS2TCNCheckIssuedCardsReq_QNAME,
                MS2TCNCheckIssuedCardsReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link TCN2MSIssuedCardDLReqType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN2MS_IssuedCardDL_Req")
    public JAXBElement<TCN2MSIssuedCardDLReqType> createTCN2MSIssuedCardDLReq(
            TCN2MSIssuedCardDLReqType value) {
        return new JAXBElement<TCN2MSIssuedCardDLReqType>(
                _TCN2MSIssuedCardDLReq_QNAME, TCN2MSIssuedCardDLReqType.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCNReceiptType }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "TCN_Receipt")
    public JAXBElement<TCNReceiptType> createTCNReceipt(TCNReceiptType value) {
        return new JAXBElement<TCNReceiptType>(_TCNReceipt_QNAME,
                TCNReceiptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link MS2TCNCheckIssuedCardsResType }{@code >}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu.cec.tren.tcn", name = "MS2TCN_CheckIssuedCards_Res")
    public JAXBElement<MS2TCNCheckIssuedCardsResType> createMS2TCNCheckIssuedCardsRes(
            MS2TCNCheckIssuedCardsResType value) {
        return new JAXBElement<MS2TCNCheckIssuedCardsResType>(
                _MS2TCNCheckIssuedCardsRes_QNAME,
                MS2TCNCheckIssuedCardsResType.class, null, value);
    }

}
