//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SearchedDriver_TCN2MS_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SearchedDriver_TCN2MS_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}SearchedDriver_MS2TCN_ReqType">
 *       &lt;sequence>
 *         &lt;element name="MemberState" type="{urn:eu.cec.tren.tcn}MemberStateType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SearchStatusCode" use="required" type="{urn:eu.cec.tren.tcn}CIC_TCN2MS_SearchStatusCodeEnumType" />
 *       &lt;attribute name="SearchStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchedDriver_TCN2MS_ResType", propOrder = { "memberState" })
public class SearchedDriverTCN2MSResType extends SearchedDriverMS2TCNReqType {

    @XmlElement(name = "MemberState", required = true)
    protected List<MemberStateType> memberState;
    @XmlAttribute(name = "SearchStatusCode", required = true)
    protected CICTCN2MSSearchStatusCodeEnumType searchStatusCode;
    @XmlAttribute(name = "SearchStatusMessage")
    protected String searchStatusMessage;

    /**
     * Gets the value of the memberState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the memberState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getMemberState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberStateType }
     * 
     * 
     */
    public List<MemberStateType> getMemberState() {
        if (memberState == null) {
            memberState = new ArrayList<MemberStateType>();
        }
        return this.memberState;
    }

    /**
     * Gets the value of the searchStatusCode property.
     * 
     * @return possible object is {@link CICTCN2MSSearchStatusCodeEnumType }
     * 
     */
    public CICTCN2MSSearchStatusCodeEnumType getSearchStatusCode() {
        return searchStatusCode;
    }

    /**
     * Sets the value of the searchStatusCode property.
     * 
     * @param value
     *            allowed object is {@link CICTCN2MSSearchStatusCodeEnumType }
     * 
     */
    public void setSearchStatusCode(CICTCN2MSSearchStatusCodeEnumType value) {
        this.searchStatusCode = value;
    }

    /**
     * Gets the value of the searchStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSearchStatusMessage() {
        return searchStatusMessage;
    }

    /**
     * Sets the value of the searchStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSearchStatusMessage(String value) {
        this.searchStatusMessage = value;
    }

}
