//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SearchedDriver_MS2TCN_ReqType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SearchedDriver_MS2TCN_ReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}SearchedDriverType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="IssuingMemberStateCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchedDriver_MS2TCN_ReqType")
@XmlSeeAlso( { SearchedDriverTCN2MSResType.class })
public class SearchedDriverMS2TCNReqType extends SearchedDriverType {

    @XmlAttribute(name = "IssuingMemberStateCode")
    protected String issuingMemberStateCode;

    /**
     * Gets the value of the issuingMemberStateCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssuingMemberStateCode() {
        return issuingMemberStateCode;
    }

    /**
     * Sets the value of the issuingMemberStateCode property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssuingMemberStateCode(String value) {
        this.issuingMemberStateCode = value;
    }

}
