//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SearchCriteria_TCN2MS_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCriteria_TCN2MS_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}SearchCriteria_MS2TCN_ReqType">
 *       &lt;sequence>
 *         &lt;element name="MSContactInfo" type="{urn:eu.cec.tren.tcn}MSContactInfoType" minOccurs="0"/>
 *         &lt;element name="CardDetails" type="{urn:eu.cec.tren.tcn}CardDetailsCCSType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SearchStatusCode" use="required" type="{urn:eu.cec.tren.tcn}CCS_TCN2MS_SearchStatusCodeEnumType" />
 *       &lt;attribute name="SearchStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCriteria_TCN2MS_ResType", propOrder = { "msContactInfo",
        "cardDetails" })
public class SearchCriteriaTCN2MSResType extends SearchCriteriaMS2TCNReqType {

    @XmlElement(name = "MSContactInfo")
    protected MSContactInfoType msContactInfo;
    @XmlElement(name = "CardDetails")
    protected CardDetailsCCSType cardDetails;
    @XmlAttribute(name = "SearchStatusCode", required = true)
    protected CCSTCN2MSSearchStatusCodeEnumType searchStatusCode;
    @XmlAttribute(name = "SearchStatusMessage")
    protected String searchStatusMessage;

    /**
     * Gets the value of the msContactInfo property.
     * 
     * @return possible object is {@link MSContactInfoType }
     * 
     */
    public MSContactInfoType getMSContactInfo() {
        return msContactInfo;
    }

    /**
     * Sets the value of the msContactInfo property.
     * 
     * @param value
     *            allowed object is {@link MSContactInfoType }
     * 
     */
    public void setMSContactInfo(MSContactInfoType value) {
        this.msContactInfo = value;
    }

    /**
     * Gets the value of the cardDetails property.
     * 
     * @return possible object is {@link CardDetailsCCSType }
     * 
     */
    public CardDetailsCCSType getCardDetails() {
        return cardDetails;
    }

    /**
     * Sets the value of the cardDetails property.
     * 
     * @param value
     *            allowed object is {@link CardDetailsCCSType }
     * 
     */
    public void setCardDetails(CardDetailsCCSType value) {
        this.cardDetails = value;
    }

    /**
     * Gets the value of the searchStatusCode property.
     * 
     * @return possible object is {@link CCSTCN2MSSearchStatusCodeEnumType }
     * 
     */
    public CCSTCN2MSSearchStatusCodeEnumType getSearchStatusCode() {
        return searchStatusCode;
    }

    /**
     * Sets the value of the searchStatusCode property.
     * 
     * @param value
     *            allowed object is {@link CCSTCN2MSSearchStatusCodeEnumType }
     * 
     */
    public void setSearchStatusCode(CCSTCN2MSSearchStatusCodeEnumType value) {
        this.searchStatusCode = value;
    }

    /**
     * Gets the value of the searchStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSearchStatusMessage() {
        return searchStatusMessage;
    }

    /**
     * Sets the value of the searchStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSearchStatusMessage(String value) {
        this.searchStatusMessage = value;
    }

}
