//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SearchedDriver_MS2TCN_ResType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SearchedDriver_MS2TCN_ResType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:eu.cec.tren.tcn}SearchedDriver_TCN2MS_ReqType">
 *       &lt;sequence>
 *         &lt;element name="DriverDetails" type="{urn:eu.cec.tren.tcn}DriverDetailsCICType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SearchStatusCode" use="required" type="{urn:eu.cec.tren.tcn}CIC_MS2TCN_SearchStatusCodeEnumType" />
 *       &lt;attribute name="SearchStatusMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchedDriver_MS2TCN_ResType", propOrder = { "driverDetails" })
public class SearchedDriverMS2TCNResType extends SearchedDriverTCN2MSReqType {

    @XmlElement(name = "DriverDetails")
    protected List<DriverDetailsCICType> driverDetails;
    @XmlAttribute(name = "SearchStatusCode", required = true)
    protected CICMS2TCNSearchStatusCodeEnumType searchStatusCode;
    @XmlAttribute(name = "SearchStatusMessage")
    protected String searchStatusMessage;

    /**
     * Gets the value of the driverDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the driverDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDriverDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverDetailsCICType }
     * 
     * 
     */
    public List<DriverDetailsCICType> getDriverDetails() {
        if (driverDetails == null) {
            driverDetails = new ArrayList<DriverDetailsCICType>();
        }
        return this.driverDetails;
    }

    /**
     * Gets the value of the searchStatusCode property.
     * 
     * @return possible object is {@link CICMS2TCNSearchStatusCodeEnumType }
     * 
     */
    public CICMS2TCNSearchStatusCodeEnumType getSearchStatusCode() {
        return searchStatusCode;
    }

    /**
     * Sets the value of the searchStatusCode property.
     * 
     * @param value
     *            allowed object is {@link CICMS2TCNSearchStatusCodeEnumType }
     * 
     */
    public void setSearchStatusCode(CICMS2TCNSearchStatusCodeEnumType value) {
        this.searchStatusCode = value;
    }

    /**
     * Gets the value of the searchStatusMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSearchStatusMessage() {
        return searchStatusMessage;
    }

    /**
     * Sets the value of the searchStatusMessage property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSearchStatusMessage(String value) {
        this.searchStatusMessage = value;
    }

}
