//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 08:59:42 PM EET 
//

package com.iba.tachonet.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WorkshopDetailsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WorkshopDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="WorkshopName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="WorkshopAddress" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Surname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkshopDetailsType")
public class WorkshopDetailsType {

    @XmlAttribute(name = "WorkshopName", required = true)
    protected String workshopName;
    @XmlAttribute(name = "WorkshopAddress", required = true)
    protected String workshopAddress;
    @XmlAttribute(name = "Surname")
    protected String surname;
    @XmlAttribute(name = "FirstName")
    protected String firstName;
    @XmlAttribute(name = "BirthDate")
    protected String birthDate;

    /**
     * Gets the value of the workshopName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWorkshopName() {
        return workshopName;
    }

    /**
     * Sets the value of the workshopName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWorkshopName(String value) {
        this.workshopName = value;
    }

    /**
     * Gets the value of the workshopAddress property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWorkshopAddress() {
        return workshopAddress;
    }

    /**
     * Sets the value of the workshopAddress property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setWorkshopAddress(String value) {
        this.workshopAddress = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

}
